### ISSUE TITLE
Unable to use layer with python 3.6

### ISSUE THREAD

**Issue by hoefling** [django/asgi_ipc#31]
First thought this is the same issue as in #26 as I got the same error in a docker container built on top of `python:3.6.2-stretch`, but also reproducible on a host machine. Using example from the readme:

```
$ pip3.6 install --user asgi_ipc
Collecting asgi_ipc
  Using cached asgi_ipc-1.4.0-py2.py3-none-any.whl
Collecting msgpack-python (from asgi_ipc)
Collecting asgiref~=1.1.2 (from asgi_ipc)
  Using cached asgiref-1.1.2-py2.py3-none-any.whl
Collecting posix-ipc>=1.0.0 (from asgi_ipc)
Requirement already satisfied: six in /usr/lib64/python3.6/site-packages (from asgi_ipc)
Installing collected packages: msgpack-python, asgiref, posix-ipc, asgi-ipc
Successfully installed asgi-ipc-1.4.0 asgiref-1.1.2 msgpack-python-0.4.8 posix-ipc-1.0.0
$ 
$ python3.6
Python 3.6.1 (default, Apr 26 2017, 12:37:57) 
[GCC 6.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import asgi_ipc
>>> import asgi_ipc as asgi
>>> channel_layer = asgi.IPCChannelLayer(
...     prefix="aeracode",
...     message_memory=200 * 1024 * 1024,
... )
>>> channel_layer.send("my_channel", {"text": "Hello ASGI"})
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/hoefling/.local/lib64/python3.6/site-packages/asgi_ipc/core.py", line 61, in send
    channel_size = self.message_store.length(channel)
  File "/home/hoefling/.local/lib64/python3.6/site-packages/asgi_ipc/store.py", line 134, in length
    with self.mutate_value() as value:
  File "/usr/lib64/python3.6/contextlib.py", line 82, in __enter__
    return next(self.gen)
  File "/home/hoefling/.local/lib64/python3.6/site-packages/asgi_ipc/store.py", line 50, in mutate_value
    value = pickle.load(self.mmap)
_pickle.UnpicklingError: invalid load key, '\x00'.
>>>
```

Not reproducible with python 3.5:

```
$ python3.5
Python 3.5.3 (default, Mar 25 2017, 06:59:48) 
[GCC 6.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import asgi_ipc as asgi
>>> channel_layer = asgi.IPCChannelLayer(
...     prefix="aeracode",
...     message_memory=200 * 1024 * 1024,
... )
>>> channel_layer.send("my_channel", {"text": "Hello ASGI"})
>>> exit()
```

**Comment by proofit404** [comment]
Hi, did you try package version from master? I'm not sure we released related fix.

**Comment by hoefling** [comment]
Indeed it works from trunk; requesting new release then...

**Comment by andrewgodwin** [comment]
Just put out 1.4.1.

**Comment by mheppner** [comment]
I'm still getting this error with both 1.4.1 and the latest version from master, using **Alpine Linux 3.6**. The key is a different value though (`\xff`), so I'm not sure if this is related or not. Do you want this as a separate issue?

```
Python 3.6.1 (default, May  2 2017, 15:16:41)
[GCC 6.3.0] on linux
```

```
asgi-ipc==1.4.1
asgiref==1.1.
channels==1.1.8
daphne==1.3.0
Django==1.11.6
posix-ipc==1.0.0
```


```python
  File "./manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/lib/python3.6/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/usr/lib/python3.6/site-packages/django/core/management/__init__.py", line 356, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/lib/python3.6/site-packages/django/core/management/base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/lib/python3.6/site-packages/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/usr/lib/python3.6/site-packages/channels/management/commands/runworker.py", line 83, in handle
    worker.run()
  File "/usr/lib/python3.6/site-packages/channels/worker.py", line 87, in run
    channel, content = self.channel_layer.receive_many(channels, block=True)
  File "/usr/lib/python3.6/site-packages/asgiref/base_layer.py", line 43, in receive_many
    return self.receive(channels, block)
  File "/usr/lib/python3.6/site-packages/asgi_ipc/core.py", line 83, in receive
    message = self.message_store.pop(channel)
  File "/usr/lib/python3.6/site-packages/asgi_ipc/store.py", line 123, in pop
    with self.mutate_value() as value:
  File "/usr/lib/python3.6/contextlib.py", line 82, in __enter__
    return next(self.gen)
  File "/usr/lib/python3.6/site-packages/asgi_ipc/store.py", line 57, in mutate_value
    value = pickle.load(self.mmap)
_pickle.UnpicklingError: invalid load key, '\xff'
```
